Only use many=True argument if request method is POST AND there is data in the request
If self.request.data is not confirmed to be present,
`kwargs['many'] =True` is always used, which is casuing the
error: `ListSerializer` object has no attribute 'fields'

https://dev.izeni.net/care-adopt/care-adopt-backend/issues/59